### PR TITLE
ML-resource-added

### PR DESCRIPTION
**Pull request by pooja2299**
Added Machine Learning TV youtube channel as a resource for Machine Learning.

### CODE REVIEW

**Review by Parasgupta44 — COMMENTED** [review]
Hi, there's inconsistency on line 308 for json...a comma is missing !! Can you rectify it so that I can merge.
Also, thanks for taking the time to contribute !

**Comment by pooja2299** [comment]
Sure! and Thank you so much for detecting the error. I was wondering why its showing error.

**Review by Parasgupta44 — APPROVED** [review]

**Comment by Parasgupta44** [comment]
Merged for deployment !!

**Comment by pooja2299** [comment]
Thank you.

**Pull request merged**
