### PR TITLE
Feat/style and structure

### PR DESCRIPTION
**Pull request by Tailine**
Structure application by creating components and refactoring some of the code and also update application style.
ml_resources

### CODE REVIEW

**Comment by Parasgupta44** [comment]
@Tailine Thanks for this.
We started migrating to TypeScript , also there are some conflicts with this PR.  Once you get the time, can you pull the latest from master and look into it.

**Comment by Tailine** [comment]
@Parasgupta44 Sure I'll look at it.

**Review by Parasgupta44 — APPROVED** [review]

**Comment by Parasgupta44** [comment]
@Tailine Thanks for contributing.
The app is much more modular and neat now. (Looks pretty awesome too !!)

**Comment by Tailine** [comment]
Thanks @Parasgupta44 ! Happy to help!

**Pull request merged**
