### PR TITLE
added a book by Aurélien Géron

### PR DESCRIPTION
**Pull request by sloorush**
Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow by Aurélien Géron. Solves Issue #1

### CODE REVIEW

**Comment by Parasgupta44** [comment]
Hi @r-ush . Thanks for contributing.
This book is strictly copyrighted by O'REILLY I suppose. If you can find some other link (not the gdrive one) for this, we can merge it.

**Comment by sloorush** [comment]
Done @Parasgupta44

**Comment by Parasgupta44** [comment]
Merged for deployment. Thanks for contributing 🐱‍👤

**Comment by sloorush** [comment]
Yay, thanks!

**Pull request merged**
